rateLimiter:
  identity:
    key: ipv4
    header: X-Forwarded-For
  client: # 클라이언트의 전체 처리량 제한
    limit: 50
    windowSeconds: 60
  apis: # 특정 API 처리량 제한
    - key: comment_write
      path:
        expression: regex
        value: /api/comment
      method: POST
      limit: 5
      windowSeconds: 60