rateLimiter:
  strategy: sliding_window_counter
  # token bucket, leaky bucket, fixed window counter, sliding window counter, sliding_window_log
  identity:
    key: ipv4
    header: X-Forwarded-For
  client: # 클라이언트의 전체 처리량 제한
    limit: 50
    windowSeconds: 60
  apis: # 특정 API 처리량 제한
    - identifier: comment_write
      path:
        expression: regex
        value: ^/api/item/\d+/comment$
      method: POST
      limit: 5
      windowSeconds: 60
      refillSeconds: 60 # 토큰 버킷 알고리즘의 경우 토큰 리필 시간
      expireSeconds: 3600
  target: https://gongnomok.com # 통과된 요청이 전달될 도메인
redis:
  host: localhost
  port: 6379
  password:
  db: 0
