version: "3.9"

x-common: &common
  build:
    context: ..
    dockerfile: docker/Dockerfile
  platform: linux/amd64
  restart: unless-stopped
  ports:
    - "8081:8081"
  volumes:
    - ../config.yml:/etc/gate-limiter/config.yml:ro
  environment:
    - GATE_LIMITER_CONFIG=/etc/gate-limiter/config.yml
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
    interval: 30s
    timeout: 5s
    retries: 3

services:
  gate-limiter:
    <<: *common
    image: sjhn/gate-limiter:${GATE_LIMITER_TAG:-latest}